/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "dsp.h"
/* Header for class com_example_audiotcp_DSPforJNI */

#ifndef _Included_com_catchwave_jni_DSPforJNI
#define _Included_com_catchwave_jni_DSPforJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_audiotcp_DSPforJNI
 * Method:    DSPfromJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_catchwave_jni_DSPforJNI_DSPfromJNI(
		JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_audiotcp_DSPforJNI
 * Method:    DSPfromLOG
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_catchwave_jni_DSPforJNI_DSPfromLOG
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
